### ISSUE TITLE
Annotation in wrong position for indented code

### ISSUE THREAD

**Issue by casparvitch** [SublimeLinter/SublimeLinter-chktex#17]
Howdy!

Thanks for the plugin, I find it very helpful. This bug is not a game-changer, but thought I'd submit it anyway.

When the LaTeX source is indented, sublimelinter-chktex doesn't correctly identify the position of warnings/errors etc.

### Source:
```
\begin{document}


\section{Introduction}

	[colors as in Fig.~\ref{}(l)], illustrating the build-up of both internal and external currents.

\end{document}
```

### ChkTeX (CLI) output:
```
ChkTeX v1.7.6 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.
Warning 36 in untitled.tex line 8: You should put a space in front of parenthesis.
        [colors as in Fig.~\ref{}(l)], illustrating the build-up of both internal and external currents.  
                                 ^
No errors printed; One warning printed; No user suppressed warnings; No line suppressed warnings.
See the manual for how to suppress some or all of these warnings/errors.
```

### Sumblimelinter-ChkTex:
![image](https://user-images.githubusercontent.com/49226876/137848508-1e372c7d-1b1c-4232-8dc7-4552c87f8688.png)

I had a look at the code to see if I could find the issue, but my regexp skills are non-existent so I hit a wall :)

Cheers

**Comment by ngraymon** [comment]
### my best guess at the problem so far
Is the problem to do with SublimeLinter's default approach to column positions?
It says [here](http://www.sublimelinter.com/en/latest/linter_attributes.html#word-re) that 
> If a linter reports a column position, SublimeLinter highlights the nearest word at that point. By default, SublimeLinter uses the regex pattern r'^([-\w]+)' to determine what is a word.

However I can't replicate your issue.
If I make a new file with the same content it correctly identifies the issue starting at the left parenthesis at column 30 and highlights it with yellow squiggly. 

Originally I thought I had this problem, then it seemed to magically go away... I have no idea.
Regardless here were my thoughts while trying to debug this.

### Trying to understand how the linter works
Since I already went to the trouble of trying to understand this I might as well post it.
[Further reading](https://www.sublimelinter.com/en/v3.10.10/linter_attributes.html#regex) indicates the regular expressions are [python regular expressions](http://docs.python.org/3/library/re.html#regular-expression-syntax) where
`(?...)` indicates "extension notation"
Looks like `(?P<line>\d+)` makes
> the substring matched by the group is accessible via the symbolic group name _name_

So then
```
regex = (
    r'^(?P<line>\d+):(?P<col>\d+) '
    r'(?:(?P<error>Error)|(?P<warning>Warning)) '
    r'(?P<message>.+)'
)
```
is really
```
regex = (
    ^(\d+):(\d+)
    r'(?:(Error)|(Warning)) '
    r'(.+)'
)
```

If I create a dummy file with your exact content and run `cmd = 'chktex -wall "-f%l:%c %k %k %n: %m\n"'` then I get
```
7:2 Warning Warning 30: Multiple spaces detected in input.\n7:30 Warning Warning 36: You should put a space in front of parenthesis.\n
```
but the 30 warnings are ignored so we only care about 
```
7:30 Warning Warning 36: You should put a space in front of parenthesis.\n
```
[which does match correct ](regexr.com/6qfmi) and the first group `P<line>` is 7 and `P<col>` is 30.

If I then remove the indent and rerun ChkTek I get:
```
7:26 Warning Warning 36: You should put a space in front of parenthesis.\n
```
where the `P<col>` group would be 26.
So it seems like things work on my end?

**Comment by casparvitch** [comment]
Working for me now too, unsure what has changed!
